try {
  throw 'error';
}
catch(e){
  console.log(e);
}

console.log('hey')